### ISSUE TITLE
Docker compose

### ISSUE THREAD

**Issue by TheCodingDutchman** [Emurgo/tangata-manu#161]
Hi, I'm having some issues with getting everything to run inside docker. 
It would be quite nice if there would be a prewritten docker-compose.yml file that we could use to edit and make running this easier. This would also allow us to run it behind a reverse proxy with for example traefik.

I was thinking about something like this
```yaml
version: '3'

services:
  postgres:
    image: 'postgres:11.2'
    container_name: 'postgres'
    networks:
      - tangatamanu
    volumes:
      - "db:/var/lib/postgresql/data"
    environment:
      postgres_password: 'PASSWORD'
  tangatamanu:
    build: ./services/tangatamanu # This is the docker file that already exists in the docker folder
    container_name: 'tangata-manu'
    restart: unless-stopped
    networks:
     - tangatamanu
    volumes:
      - './data:/app'
    depends_on:
      - postgres
      - bridge
    environment:
      postgres_password: 'PASSWORD'
      postgres_host: postgres
      postgres_port: 5432
      postgres_db: 'tangatamanu'
      bridge_host: httpbridge
      bridge_port: 8082
    httpbridge:
       container_name: 'http-bridge'
       networks:
         - tangatamanu
       build: ./services/httpbridge # A Dockerfile needs to be created for this, I'm not that good with that so someone else would need to do that
       environment:
         port: 8082
         template: 'testnet2'
       
volumes:
  db:

networks:
  tangatamanu:
```

Is this possible?
